# Generated by Django 3.1.1 on 2022-06-15 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer_reg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=50)),
                ('tage', models.IntegerField()),
                ('tphno', models.BigIntegerField(max_length=50)),
                ('city', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Trainer.city')),
            ],
        ),
        migrations.CreateModel(
            name='Trainer_Assign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('course', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Trainer.course')),
                ('t_name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Trainer.trainer_reg')),
            ],
        ),
    ]
