# Generated by Django 3.1.1 on 2022-06-15 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trainer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer_reg',
            name='tphno',
            field=models.BigIntegerField(),
        ),
    ]
