# Generated by Django 3.1.1 on 2022-06-15 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trainer', '0002_auto_20220615_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer_reg',
            name='password',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
